server:
  port: 7500

spring:
  datasource:
    username: root
    password: wql19990322
    url: jdbc:mysql://localhost:3306/gulimail_wms
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: gulimail-ware
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
